name: chemical-clocks
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.12
    - numpy>=2.0
    - pandas
    - matplotlib
    - astropy
    - jupyterlab
    - scipy
    - scikit-learn
    - statsmodels
    - pip
    - pip:
        - sdss-access
