name: chemical-clocks
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.12
    - numpy>=2.0
    - pandas
    - matplotlib
    - astropy
    - jupyterlab
    - scipy
    - conda-forge::gsl
    - galpy
    - tqdm
    - numba
    - pip
    - pip:
        - vice>=1.3.1
        - dill
        - gala
